### ISSUE TITLE
Trackman does not read club data - while ball is hit in the middle of the blue alignment box

### ISSUE THREAD

**Issue by ajaygautam** [golflounge18/Trackman-Integration#8]

**Comment by ajaygautam** [comment]
We have not been able to establish a pattern of when, why it happens.
Everything reads, but club data is missing!

**Comment by jktrackman** [comment]
This can be due to many factors

- Miss hits
- Smash factor closer to 1.0 (makes it harder for us to distinguish the club and ball as they are moving away from the radar at similar speeds - slower swing speeds or using wedges)
- Drastic golf swings where the club head leaves the "cone" of the radar too quickly (mostly seen on over the top swings)
